# Generated by Django 3.2.8 on 2026-03-04 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255, verbose_name='图书名字')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='图书价格')),
                ('read_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读人数')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='评分')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='图书出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版时间')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='总字数（单位：万字）')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '图书信息',
                'verbose_name_plural': '图书信息',
                'db_table': 'spider_book',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='userlist',
            options={'managed': True, 'verbose_name': '前台用户', 'verbose_name_plural': '前台用户'},
        ),
        migrations.RemoveField(
            model_name='sendlist',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userexpect',
            name='place',
        ),
        migrations.AddField(
            model_name='userexpect',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图书类型'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='pass_word',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='user_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名'),
        ),
        migrations.DeleteModel(
            name='JobData',
        ),
        migrations.AddField(
            model_name='sendlist',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job.spiderbook'),
        ),
    ]
