# Generated by Django 3.2.8 on 2026-03-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20260304_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpect',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
